### ISSUE TITLE
LWRP users_manage always fires

### ISSUE THREAD

**Issue by kkeane** [sous-chefs/users#77] opened 2015-01-25 18:16 UTC
The users_manage resource is not fully idempotent; it seems to fire on every run.

I traced the culprit down to the converge_by statement in the LWRP (there is only one, related to creating the .ssh directory). Removing that statement (and the corresponding 'end' of of course) will make the resource work idempotently as expected.

**Comment by jtimberman** [comment] 2015-01-26 15:08
The `converge_by` block is required for why-run mode support.

**Comment by dblessing** [comment] 2015-02-12 21:26
@jtimberman Does `converge_by` automatically make it spit out `- would create /home/<user>/.ssh` everytime? I am seeing the same thing as @kkeane where Chef Manage reports it as a changed resource every single run. See screenshot...

![screen shot 2015-02-12 at 3 25 32 pm](https://cloud.githubusercontent.com/assets/2394772/6177338/6e0f55fa-b2cb-11e4-9446-4ff6ac6610e2.png)

**Comment by dblessing** [comment] 2015-02-12 21:33
Actually, this looks like it has already been addressed a year ago in 53d612bd4f367cbdaec0f232221d262e81189ae0 Now we just need a release pushed to the Supermarket :)

**Comment by digitalhero86** [comment] 2015-03-24 22:06
Is this going to be pushed to the Supermarket anytime soon?

**Comment by dblessing** [comment] 2015-03-24 22:12
I believe it was pushed recently. I haven't had a chance to test.

**Comment by digitalhero86** [comment] 2015-03-25 15:17
Thanks for the quick response,   I checked my code and see that I do in fact have the changes made.   Unfortunately,this doesn't seem to of fixed the issue for me.   I get an error the first time I run chef-client with a :remove statement and after that it works properly again.

**Comment by iennae** [comment] 2016-01-25 23:51
@dblessing @kkeane @digitalhero86 are you still seeing this issue with user_manage ? I'm not seeing the issue in my tests with Test Kitchen at this point.

Thanks!

**Comment by frank-m** [comment] 2021-03-16 07:53
After testing I have not been able to reproduce these issues. As there has been no reply since 2016, I am going to close this issue for now.

If you still run into these issues, please open a new issue.

**Closed by frank-m** 2021-03-16 07:53 UTC
